     unit: data.unit,
        semester: data.semester,
        course: data.course,
        admission_year: data.admissionYear,
        ktu_id: data.ktuId,
        name: data.name,
        student_id: userId, // ✅ Use the passed userId
        gender: data.gender,
        dob: data.dob,
        contact_number: data.contactNumber,
        whatsapp_number: data.whatsappNumber,
        religion: data.religion,
        community: data.community,
        blood_group: data.bloodGroup,
        height: data.height ? parseInt(data.height) : null,
        weight: data.weight ? parseInt(data.weight) : null,
        district: data.district,
        taluk: data.taluk,
        village: data.village,
        pincode: data.pincode,
        permanent_address: data.permanentAddress,
        parent_name: data.parent,
        parent_contact: data.parentContact,
        photo_url: photoUrl,
        signature_url: signatureUrl,
        languages_known: data.languagesKnown || [],
        status: "pending", // Default status
        created_at: new Date().toISOString(),